name: Create Repository Zip

on:
  workflow_dispatch:  # Manual trigger

jobs:
  create-zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create zip archive
      run: |
        # Create zip file with maximum compression (level 9)
        zip -r -9 Player_No_456.zip . -x '*.git*'
        
    - name: Upload zip artifact
      uses: actions/upload-artifact@v4
      with:
        name: Player_No_456.zip
        path: Player_No_456.zip